question_data = [

    {"category": "Entertainment: Video Games",
     "type": "multiple",
     "difficulty": "medium",
     "question": "When was the original Star Wars: Battlefront II released?",
     "correct_answer": "October 31, 2005",
     "incorrect_answers": ["December 18, 2004", "November 21, 2006", "September 9, 2007"]},
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "medium",
     "question": "What is the defining characteristic of someone who is described as hirsute?",
     "correct_answer": "Hairy",
     "incorrect_answers": ["Rude", "Funny", "Tall"]},
    {"category": "Entertainment: Music",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Scottish producer Calvin Harris is from the town of Dumfries, Scotland.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Sports", "type": "multiple", "difficulty": "medium",
     "question": "Which nation hosted the FIFA World Cup in 2006?", "correct_answer": "Germany",
     "incorrect_answers": ["United Kingdom", "Brazil", "South Africa"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "Rabbits are rodents.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "multiple", "difficulty": "medium",
     "question": "Who voiced Metalbeard in &quot;The Lego Movie&quot;?", "correct_answer": "Nick Offerman",
     "incorrect_answers": ["Liam Neeson", "Morgan Freeman", "Will Arnet"]},
    {"category": "Science: Gadgets", "type": "multiple", "difficulty": "medium",
     "question": "In what year was the Oculus Rift revealed to the public through a Kickstarter campaign?",
     "correct_answer": "2012", "incorrect_answers": ["2010", "2011", "2013"]},
    {"category": "Politics", "type": "boolean", "difficulty": "medium",
     "question": "The State of Queensland, Australia voted NO to a referendum for daylight savings in 1992.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "Down Syndrome is usually caused by an extra copy of which chromosome?", "correct_answer": "21",
     "incorrect_answers": ["23", "15", "24"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "The Korean War ended in 1953 without any ceasefire.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]
